import { AzureResourceRow } from "../../types";

export const containers: AzureResourceRow[] = [
  {
    id: "/subscriptions/215abcdf-e871-479a-9d1c-17fpqr915095",
    name: "Azure subscription 1",
    type: "microsoft.resources/subscriptions",
    tenantId: "aabbccdd-eeff-gghh-iijj-123456789abc",
    kind: "",
    location: "",
    resourceGroup: "",
    subscriptionId: "215abcdf-e871-479a-9d1c-17fpqr915095",
    managedBy: "",
    sku: null,
    plan: null,
    properties: {
      managementGroupAncestorsChain: [
        {
          displayName: "Tenant Root Group",
          name: "aabbccdd-eeff-gghh-iijj-123456789abc",
        },
      ],
      subscriptionPolicies: {
        locationPlacementId: "Public_2014-09-01",
        spendingLimit: "On",
        quotaId: "abcd1234",
      },
      managedByTenants: [],
      state: "Enabled",
    },
    tags: null,
    identity: null,
    zones: null,
    extendedLocation: null,
  },
  {
    id: "/subscriptions/215abcdf-e871-479a-9d1c-17fpqr915095/resourcegroups/networkwatcherrg",
    name: "NetworkWatcherRG",
    type: "microsoft.resources/subscriptions/resourcegroups",
    tenantId: "aabbccdd-eeff-gghh-iijj-123456789abc",
    kind: "",
    location: "westus2",
    resourceGroup: "networkwatcherrg",
    subscriptionId: "215abcdf-e871-479a-9d1c-17fpqr915095",
    managedBy: "",
    sku: null,
    plan: null,
    properties: {
      provisioningState: "Succeeded",
    },
    tags: null,
    identity: null,
    zones: null,
    extendedLocation: null,
  },
  {
    id: "/subscriptions/215abcdf-e871-479a-9d1c-17fpqr915095/resourcegroups/rg-uabcd12-0",
    name: "rg-uabcd12-0",
    type: "microsoft.resources/subscriptions/resourcegroups",
    tenantId: "aabbccdd-eeff-gghh-iijj-123456789abc",
    kind: "",
    location: "westus2",
    resourceGroup: "rg-uabcd12-0",
    subscriptionId: "215abcdf-e871-479a-9d1c-17fpqr915095",
    managedBy: "",
    sku: null,
    plan: null,
    properties: {
      provisioningState: "Succeeded",
    },
    tags: null,
    identity: null,
    zones: null,
    extendedLocation: null,
  },
  {
    id: "/subscriptions/215abcdf-e871-479a-9d1c-17fpqr915095/resourcegroups/rg-uabcd12-1",
    name: "rg-uabcd12-1",
    type: "microsoft.resources/subscriptions/resourcegroups",
    tenantId: "aabbccdd-eeff-gghh-iijj-123456789abc",
    kind: "",
    location: "westus2",
    resourceGroup: "rg-uabcd12-1",
    subscriptionId: "215abcdf-e871-479a-9d1c-17fpqr915095",
    managedBy: "",
    sku: null,
    plan: null,
    properties: {
      provisioningState: "Succeeded",
    },
    tags: null,
    identity: null,
    zones: null,
    extendedLocation: null,
  },
  {
    id: "/subscriptions/215abcdf-e871-479a-9d1c-17fpqr915095/resourcegroups/rg-uabcd12-2",
    name: "rg-uabcd12-2",
    type: "microsoft.resources/subscriptions/resourcegroups",
    tenantId: "aabbccdd-eeff-gghh-iijj-123456789abc",
    kind: "",
    location: "westus2",
    resourceGroup: "rg-uabcd12-2",
    subscriptionId: "215abcdf-e871-479a-9d1c-17fpqr915095",
    managedBy: "",
    sku: null,
    plan: null,
    properties: {
      provisioningState: "Succeeded",
    },
    tags: null,
    identity: null,
    zones: null,
    extendedLocation: null,
  },
  {
    id: "/subscriptions/215abcdf-e871-479a-9d1c-17fpqr915095/resourcegroups/resgrp.with.period",
    name: "resgrp.with.period",
    type: "microsoft.resources/subscriptions/resourcegroups",
    tenantId: "aabbccdd-eeff-gghh-iijj-123456789abc",
    kind: "",
    location: "westus2",
    resourceGroup: "resgrp.with.period",
    subscriptionId: "215abcdf-e871-479a-9d1c-17fpqr915095",
    managedBy: "",
    sku: null,
    plan: null,
    properties: {
      provisioningState: "Succeeded",
    },
    tags: {},
    identity: null,
    zones: null,
    extendedLocation: null,
  },
];
