import { GraphResponseObject } from "../enrichPrincipals";

export const graphResponse: GraphResponseObject = {
  response: [
    {
      "@odata.type": "#microsoft.graph.servicePrincipal",
      id: "5a908450-60xx-4c5y-9a26-4z95d163pqr5",
      deletedDateTime: null,
      accountEnabled: true,
      alternativeNames: [],
      appDisplayName: "sp-test-serviceprincipal",
      appDescription: null,
      appId: "cdb2a9be-1050-4d7f-pqre-e04daa123909",
      applicationTemplateId: null,
      appOwnerOrganizationId: "aabbccdd-eeff-gghh-iijj-123456789abc",
      appRoleAssignmentRequired: false,
      createdByAppId: "18ed3123-a475-4ccb-b669-pqrbc9f2a36e",
      createdDateTime: "2026-02-07T15:54:44Z",
      description: null,
      disabledByMicrosoftStatus: null,
      displayName: "sp-test-serviceprincipal",
      homepage: null,
      loginUrl: null,
      logoutUrl: null,
      notes: null,
      notificationEmailAddresses: [],
      preferredSingleSignOnMode: null,
      preferredTokenSigningKeyThumbprint: null,
      replyUrls: [],
      servicePrincipalNames: ["cdb2a9be-1050-4d7f-pqre-e04daa123909"],
      servicePrincipalType: "Application",
      signInAudience: "AzureADMyOrg",
      tags: ["HideApp", "WindowsAzureActiveDirectoryIntegratedApp"],
      tokenEncryptionKeyId: null,
      samlSingleSignOnSettings: null,
      addIns: [],
      appRoles: [],
      info: {
        logoUrl: null,
        marketingUrl: null,
        privacyStatementUrl: null,
        supportUrl: null,
        termsOfServiceUrl: null,
      },
      keyCredentials: [],
      oauth2PermissionScopes: [],
      passwordCredentials: [],
      resourceSpecificApplicationPermissions: [],
      verifiedPublisher: {
        displayName: null,
        verifiedPublisherId: null,
        addedDateTime: null,
      },
    },
    {
      "@odata.type": "#microsoft.graph.user",
      id: "abcd0a7c-123b-456f-9xyz-c002def8c504",
      businessPhones: [],
      displayName: "John Appleseed",
      givenName: "John",
      jobTitle: null,
      mail: null,
      mobilePhone: null,
      officeLocation: null,
      preferredLanguage: "en",
      surname: "Appleseed",
      userPrincipalName:
        "appleseed.john_outlook.com#EXT#@appleseedjohnoutlook.onmicrosoft.com",
    },
    {
      "@odata.type": "#microsoft.graph.servicePrincipal",
      id: "971765d3-3aa5-4123-9e22-65cd0bbbda8x",
      deletedDateTime: null,
      accountEnabled: true,
      alternativeNames: [],
      appDisplayName: "cloudexplorer-web",
      appDescription: null,
      appId: "c107pqrs-867c-4b6a-be9e-799f412342ab",
      applicationTemplateId: null,
      appOwnerOrganizationId: "aabbccdd-eeff-gghh-iijj-123456789abc",
      appRoleAssignmentRequired: false,
      createdByAppId: "18ed3123-a475-4ccb-b669-pqrbc9f2a36e",
      createdDateTime: "2026-02-20T15:06:29Z",
      description: null,
      disabledByMicrosoftStatus: null,
      displayName: "cloudexplorer-web",
      homepage: null,
      loginUrl: null,
      logoutUrl: null,
      notes: null,
      notificationEmailAddresses: [],
      preferredSingleSignOnMode: null,
      preferredTokenSigningKeyThumbprint: null,
      replyUrls: ["http://localhost:3000/"],
      servicePrincipalNames: ["c107pqrs-867c-4b6a-be9e-799f412342ab"],
      servicePrincipalType: "Application",
      signInAudience: "AzureADMyOrg",
      tags: ["HideApp", "WindowsAzureActiveDirectoryIntegratedApp"],
      tokenEncryptionKeyId: null,
      samlSingleSignOnSettings: null,
      addIns: [],
      appRoles: [
        {
          allowedMemberTypes: ["Application"],
          description: "give access to user read",
          displayName: "give access to user.read",
          id: "d1d449a0-1368-4854-9136-3281d14d167a",
          isEnabled: true,
          origin: "Application",
          value: "User.Read",
        },
      ],
      info: {
        logoUrl: null,
        marketingUrl: null,
        privacyStatementUrl: null,
        supportUrl: null,
        termsOfServiceUrl: null,
      },
      keyCredentials: [],
      oauth2PermissionScopes: [],
      passwordCredentials: [],
      resourceSpecificApplicationPermissions: [],
      verifiedPublisher: {
        displayName: null,
        verifiedPublisherId: null,
        addedDateTime: null,
      },
    },
    {
      "@odata.type": "#microsoft.graph.servicePrincipal",
      id: "1238b0aa-pqrs-45c1-9150-5xyza8d72fcf",
      deletedDateTime: null,
      accountEnabled: true,
      alternativeNames: [],
      appDisplayName: "test-permissions-sp",
      appDescription: null,
      appId: "123a4b9f-320a-4102-9809-b96pqrse6b13",
      applicationTemplateId: null,
      appOwnerOrganizationId: "aabbccdd-eeff-gghh-iijj-123456789abc",
      appRoleAssignmentRequired: false,
      createdByAppId: "18ed3123-a475-4ccb-b669-pqrbc9f2a36e",
      createdDateTime: "2026-02-22T10:29:15Z",
      description: null,
      disabledByMicrosoftStatus: null,
      displayName: "test-permissions-sp",
      homepage: null,
      loginUrl: null,
      logoutUrl: null,
      notes: null,
      notificationEmailAddresses: [],
      preferredSingleSignOnMode: null,
      preferredTokenSigningKeyThumbprint: null,
      replyUrls: [],
      servicePrincipalNames: ["123a4b9f-320a-4102-9809-b96pqrse6b13"],
      servicePrincipalType: "Application",
      signInAudience: "AzureADMyOrg",
      tags: ["HideApp", "WindowsAzureActiveDirectoryIntegratedApp"],
      tokenEncryptionKeyId: null,
      samlSingleSignOnSettings: null,
      addIns: [],
      appRoles: [],
      info: {
        logoUrl: null,
        marketingUrl: null,
        privacyStatementUrl: null,
        supportUrl: null,
        termsOfServiceUrl: null,
      },
      keyCredentials: [],
      oauth2PermissionScopes: [],
      passwordCredentials: [],
      resourceSpecificApplicationPermissions: [],
      verifiedPublisher: {
        displayName: null,
        verifiedPublisherId: null,
        addedDateTime: null,
      },
    },
  ],
};
