import { AzureResourceRow } from "../../types";

export const resources: AzureResourceRow[] = [
  {
    id: "/subscriptions/215abcdf-e871-479a-9d1c-17fpqr915095/resourcegroups/networkwatcherrg/providers/microsoft.network/networkwatchers/networkwatcher_westus2",
    name: "NetworkWatcher_westus2",
    type: "microsoft.network/networkwatchers",
    tenantId: "aabbccdd-eeff-gghh-iijj-123456789abc",
    kind: "",
    location: "westus2",
    resourceGroup: "networkwatcherrg",
    subscriptionId: "215abcdf-e871-479a-9d1c-17fpqr915095",
    managedBy: "",
    sku: null,
    plan: null,
    properties: {
      provisioningState: "Succeeded",
      runningOperationIds: [],
    },
    tags: null,
    identity: null,
    zones: null,
    extendedLocation: null,
  },
  {
    id: "/subscriptions/215abcdf-e871-479a-9d1c-17fpqr915095/resourcegroups/rg-uabcd12-0/providers/microsoft.compute/disks/myosdisk-uabcd12-0-0",
    name: "myosdisk-uabcd12-0-0",
    type: "microsoft.compute/disks",
    tenantId: "aabbccdd-eeff-gghh-iijj-123456789abc",
    kind: "",
    location: "westus2",
    resourceGroup: "rg-uabcd12-0",
    subscriptionId: "215abcdf-e871-479a-9d1c-17fpqr915095",
    managedBy:
      "/subscriptions/215abcdf-e871-479a-9d1c-17fpqr915095/resourceGroups/rg-uabcd12-0/providers/Microsoft.Compute/virtualMachines/vm-uabcd12-0",
    sku: {
      name: "Premium_LRS",
      tier: "Premium",
    },
    plan: null,
    properties: {
      provisioningState: "Succeeded",
      publicNetworkAccess: "Enabled",
      networkAccessPolicy: "AllowAll",
      timeCreated: "2026-02-06T15:03:50.9806064Z",
      diskSizeGB: 30,
      encryption: {
        type: "EncryptionAtRestWithPlatformKey",
      },
      diskSizeBytes: 32213303296,
      creationData: {
        createOption: "FromImage",
        imageReference: {
          id: "/Subscriptions/df490f38-cff1-4a2e-83e0-b0c1c5689269/Providers/Microsoft.Compute/Locations/westus2/Publishers/canonical/ArtifactTypes/VMImage/Offers/ubuntuserver/Skus/16.04-lts/Versions/16.04.202109281",
        },
      },
      hyperVGeneration: "V1",
      diskState: "Reserved",
      LastOwnershipUpdateTime: "2026-02-10T14:12:47.8136553Z",
      supportedCapabilities: {
        architecture: "x64",
        acceleratedNetwork: true,
      },
      uniqueId: "0a2d6ca7-pqr7-46d4-bd7d-c2cf0d1c0632",
      diskIOPSReadWrite: 120,
      diskMBpsReadWrite: 25,
      osType: "Linux",
      supportsHibernation: false,
      tier: "P4",
    },
    tags: null,
    identity: null,
    zones: null,
    extendedLocation: null,
  },
  {
    id: "/subscriptions/215abcdf-e871-479a-9d1c-17fpqr915095/resourcegroups/rg-uabcd12-0/providers/microsoft.compute/disks/myosdisk-uabcd12-1-1",
    name: "myosdisk-uabcd12-1-1",
    type: "microsoft.compute/disks",
    tenantId: "aabbccdd-eeff-gghh-iijj-123456789abc",
    kind: "",
    location: "westus2",
    resourceGroup: "rg-uabcd12-0",
    subscriptionId: "215abcdf-e871-479a-9d1c-17fpqr915095",
    managedBy:
      "/subscriptions/215abcdf-e871-479a-9d1c-17fpqr915095/resourceGroups/rg-uabcd12-0/providers/Microsoft.Compute/virtualMachines/vm-uabcd12-1",
    sku: {
      name: "Premium_LRS",
      tier: "Premium",
    },
    plan: null,
    properties: {
      provisioningState: "Succeeded",
      publicNetworkAccess: "Enabled",
      networkAccessPolicy: "AllowAll",
      timeCreated: "2026-02-06T15:03:51.0587048Z",
      diskSizeGB: 30,
      encryption: {
        type: "EncryptionAtRestWithPlatformKey",
      },
      diskSizeBytes: 32213303296,
      creationData: {
        createOption: "FromImage",
        imageReference: {
          id: "/Subscriptions/215abcdf-e871-479a-9d1c-17fpqr915095/Providers/Microsoft.Compute/Locations/westus2/Publishers/Canonical/ArtifactTypes/VMImage/Offers/UbuntuServer/Skus/16.04-LTS/Versions/16.04.202109281",
        },
      },
      hyperVGeneration: "V1",
      diskState: "Reserved",
      LastOwnershipUpdateTime: "2026-02-06T16:17:07.0099702Z",
      supportedCapabilities: {
        architecture: "x64",
        acceleratedNetwork: true,
      },
      uniqueId: "ab23cd30-pqr7-418a-9961-05892245a9c7",
      diskIOPSReadWrite: 120,
      diskMBpsReadWrite: 25,
      osType: "Linux",
      supportsHibernation: false,
      tier: "P4",
    },
    tags: null,
    identity: null,
    zones: null,
    extendedLocation: null,
  },
  {
    id: "/subscriptions/215abcdf-e871-479a-9d1c-17fpqr915095/resourcegroups/rg-uabcd12-0/providers/microsoft.compute/virtualmachines/vm-uabcd12-0",
    name: "vm-uabcd12-0",
    type: "microsoft.compute/virtualmachines",
    tenantId: "aabbccdd-eeff-gghh-iijj-123456789abc",
    kind: "",
    location: "westus2",
    resourceGroup: "rg-uabcd12-0",
    subscriptionId: "215abcdf-e871-479a-9d1c-17fpqr915095",
    managedBy: "",
    sku: null,
    plan: null,
    properties: {
      provisioningState: "Succeeded",
      timeCreated: "2026-02-06T15:03:49.5319886Z",
      networkProfile: {
        networkInterfaces: [
          {
            properties: {
              primary: false,
            },
            id: "/subscriptions/215abcdf-e871-479a-9d1c-17fpqr915095/resourceGroups/rg-uabcd12-0/providers/Microsoft.Network/networkInterfaces/nic-uabcd12-0",
          },
        ],
      },
      storageProfile: {
        imageReference: {
          publisher: "Canonical",
          version: "latest",
          exactVersion: "16.04.202109281",
          sku: "16.04-LTS",
          offer: "UbuntuServer",
        },
        dataDisks: [],
        osDisk: {
          name: "myosdisk-uabcd12-0-0",
          createOption: "FromImage",
          osType: "Linux",
          deleteOption: "Detach",
          managedDisk: {
            id: "/subscriptions/215abcdf-e871-479a-9d1c-17fpqr915095/resourceGroups/RG-uabcd12-0/providers/Microsoft.Compute/disks/myosdisk-uabcd12-0-0",
          },
          caching: "ReadWrite",
          writeAcceleratorEnabled: false,
        },
      },
      hardwareProfile: {
        vmSize: "Standard_B2ats_v2",
      },
      osProfile: {
        computerName: "hostname230630032848831819",
        requireGuestProvisionSignal: true,
        allowExtensionOperations: true,
        secrets: [],
        adminUsername: "azureuser",
        linuxConfiguration: {
          provisionVMAgent: true,
          disablePasswordAuthentication: false,
          patchSettings: {
            assessmentMode: "ImageDefault",
            patchMode: "ImageDefault",
          },
        },
      },
      vmId: "a84d0ffe-12ab-45f6-8e6e-4966c4488927",
      extended: {
        instanceView: {
          hyperVGeneration: "V1",
          powerState: {
            displayStatus: "VM deallocated",
            level: "Info",
            code: "PowerState/deallocated",
          },
        },
      },
    },
    tags: null,
    identity: {
      principalId: "07e41234-1941-4207-pqr1-3d5158amnq70",
      userAssignedIdentities: {
        "/subscriptions/215abcdf-e871-479a-9d1c-17fpqr915095/resourceGroups/resgrp.with.period/providers/Microsoft.ManagedIdentity/userAssignedIdentities/uai-lemons":
          {},
        "/subscriptions/215abcdf-e871-479a-9d1c-17fpqr915095/resourceGroups/rg-uabcd12-0/providers/Microsoft.ManagedIdentity/userAssignedIdentities/uai-uabcd12":
          {
            principalId: "1234d2bc-abcd-4511-abf6-4a7543266acd",
            clientId: "ba690b72-pqr1-42c6-8b34-1bc050fkmnb1",
          },
      },
      tenantId: "aabbccdd-eeff-gghh-iijj-123456789abc",
      type: "SystemAssigned, UserAssigned",
    },
    zones: null,
    extendedLocation: null,
  },
  {
    id: "/subscriptions/215abcdf-e871-479a-9d1c-17fpqr915095/resourcegroups/rg-uabcd12-0/providers/microsoft.compute/virtualmachines/vm-uabcd12-1",
    name: "vm-uabcd12-1",
    type: "microsoft.compute/virtualmachines",
    tenantId: "aabbccdd-eeff-gghh-iijj-123456789abc",
    kind: "",
    location: "westus2",
    resourceGroup: "rg-uabcd12-0",
    subscriptionId: "215abcdf-e871-479a-9d1c-17fpqr915095",
    managedBy: "",
    sku: null,
    plan: null,
    properties: {
      provisioningState: "Succeeded",
      timeCreated: "2026-02-06T15:03:49.8913384Z",
      networkProfile: {
        networkInterfaces: [
          {
            properties: {
              primary: false,
            },
            id: "/subscriptions/215abcdf-e871-479a-9d1c-17fpqr915095/resourceGroups/rg-uabcd12-0/providers/Microsoft.Network/networkInterfaces/nic-uabcd12-1",
          },
        ],
      },
      storageProfile: {
        imageReference: {
          publisher: "Canonical",
          version: "latest",
          exactVersion: "16.04.202109281",
          sku: "16.04-LTS",
          offer: "UbuntuServer",
        },
        dataDisks: [],
        osDisk: {
          name: "myosdisk-uabcd12-1-1",
          createOption: "FromImage",
          osType: "Linux",
          deleteOption: "Detach",
          managedDisk: {
            id: "/subscriptions/215abcdf-e871-479a-9d1c-17fpqr915095/resourceGroups/rg-uabcd12-0/providers/Microsoft.Compute/disks/myosdisk-uabcd12-1-1",
          },
          caching: "ReadWrite",
          writeAcceleratorEnabled: false,
        },
      },
      hardwareProfile: {
        vmSize: "Standard_B2ats_v2",
      },
      osProfile: {
        computerName: "hostname230630032848831819",
        requireGuestProvisionSignal: true,
        allowExtensionOperations: true,
        secrets: [],
        adminUsername: "azureuser",
        linuxConfiguration: {
          provisionVMAgent: true,
          disablePasswordAuthentication: false,
          patchSettings: {
            assessmentMode: "ImageDefault",
            patchMode: "ImageDefault",
          },
        },
      },
      vmId: "2782d31b-2970-4037-99a0-7d9c15871dbb",
      extended: {
        instanceView: {
          hyperVGeneration: "V1",
          powerState: {
            displayStatus: "VM deallocated",
            level: "Info",
            code: "PowerState/deallocated",
          },
        },
      },
    },
    tags: null,
    identity: {
      principalId: "52klm79d-9804-4123-b704-d2e568f2pqr9",
      userAssignedIdentities: {
        "/subscriptions/215abcdf-e871-479a-9d1c-17fpqr915095/resourceGroups/resgrp.with.period/providers/Microsoft.ManagedIdentity/userAssignedIdentities/uai-lemons":
          {},
      },
      tenantId: "aabbccdd-eeff-gghh-iijj-123456789abc",
      type: "SystemAssigned, UserAssigned",
    },
    zones: null,
    extendedLocation: null,
  },
  {
    id: "/subscriptions/215abcdf-e871-479a-9d1c-17fpqr915095/resourcegroups/rg-uabcd12-0/providers/microsoft.keyvault/vaults/kv-uabcd12",
    name: "kv-uabcd12",
    type: "microsoft.keyvault/vaults",
    tenantId: "aabbccdd-eeff-gghh-iijj-123456789abc",
    kind: "",
    location: "westus2",
    resourceGroup: "rg-uabcd12-0",
    subscriptionId: "215abcdf-e871-479a-9d1c-17fpqr915095",
    managedBy: "",
    sku: null,
    plan: null,
    properties: {
      provisioningState: "Succeeded",
      publicNetworkAccess: "Enabled",
      tenantId: "aabbccdd-eeff-gghh-iijj-123456789abc",
      sku: {
        name: "standard",
        family: "A",
      },
      enableRbacAuthorization: false,
      enabledForTemplateDeployment: false,
      softDeleteRetentionInDays: 90,
      enabledForDeployment: false,
      enabledForDiskEncryption: false,
      enableSoftDelete: true,
      accessPolicies: [],
      vaultUri: "https://kv-uabcd12.vault.azure.net/",
    },
    tags: {},
    identity: null,
    zones: null,
    extendedLocation: null,
  },
  {
    id: "/subscriptions/215abcdf-e871-479a-9d1c-17fpqr915095/resourcegroups/rg-uabcd12-0/providers/microsoft.managedidentity/userassignedidentities/uai-uabcd12",
    name: "uai-uabcd12",
    type: "microsoft.managedidentity/userassignedidentities",
    tenantId: "aabbccdd-eeff-gghh-iijj-123456789abc",
    kind: "",
    location: "westus2",
    resourceGroup: "rg-uabcd12-0",
    subscriptionId: "215abcdf-e871-479a-9d1c-17fpqr915095",
    managedBy: "",
    sku: null,
    plan: null,
    properties: {
      tenantId: "aabbccdd-eeff-gghh-iijj-123456789abc",
      isolationScope: "None",
      principalId: "1234d2bc-abcd-4511-abf6-4a7543266acd",
      clientId: "ba690b72-pqr1-42c6-8b34-1bc050fkmnb1",
    },
    tags: {},
    identity: null,
    zones: null,
    extendedLocation: null,
  },
  {
    id: "/subscriptions/215abcdf-e871-479a-9d1c-17fpqr915095/resourcegroups/rg-uabcd12-0/providers/microsoft.network/networkinterfaces/nic-uabcd12-0",
    name: "nic-uabcd12-0",
    type: "microsoft.network/networkinterfaces",
    tenantId: "aabbccdd-eeff-gghh-iijj-123456789abc",
    kind: "Regular",
    location: "westus2",
    resourceGroup: "rg-uabcd12-0",
    subscriptionId: "215abcdf-e871-479a-9d1c-17fpqr915095",
    managedBy: "",
    sku: null,
    plan: null,
    properties: {
      provisioningState: "Succeeded",
      defaultOutboundConnectivityEnabled: false,
      enableAcceleratedNetworking: false,
      resourceGuid: "3c312337-23f2-4e80-b9cf-d0bpqr0bamno",
      disableTcpStateTracking: false,
      ipConfigurations: [
        {
          properties: {
            provisioningState: "Succeeded",
            privateIPAddressVersion: "IPv4",
            privateIPAllocationMethod: "Dynamic",
            privateIPAddress: "10.0.2.5",
            subnet: {
              id: "/subscriptions/215abcdf-e871-479a-9d1c-17fpqr915095/resourceGroups/rg-uabcd12-0/providers/Microsoft.Network/virtualNetworks/vnet-uabcd12/subnets/snet-uabcd12",
            },
            primary: true,
          },
          name: "testconfiguration1",
          type: "Microsoft.Network/networkInterfaces/ipConfigurations",
          id: "/subscriptions/215abcdf-e871-479a-9d1c-17fpqr915095/resourceGroups/rg-uabcd12-0/providers/Microsoft.Network/networkInterfaces/nic-uabcd12-0/ipConfigurations/testconfiguration1",
          etag: 'W/"96pqrcb9-1234-44fa-a93b-4d5812378d42"',
        },
        {
          properties: {
            provisioningState: "Succeeded",
            privateIPAddressVersion: "IPv6",
            privateIPAllocationMethod: "Dynamic",
            privateIPAddress: "fd00:7ec4:2c41::4",
            subnet: {
              id: "/subscriptions/215abcdf-e871-479a-9d1c-17fpqr915095/resourceGroups/rg-uabcd12-0/providers/Microsoft.Network/virtualNetworks/vnet-uabcd12/subnets/snet-uabcd12",
            },
            publicIPAddress: {
              id: "/subscriptions/215abcdf-e871-479a-9d1c-17fpqr915095/resourceGroups/rg-uabcd12-0/providers/Microsoft.Network/publicIPAddresses/pip6-uabcd12",
            },
          },
          name: "pip6-connection",
          type: "Microsoft.Network/networkInterfaces/ipConfigurations",
          id: "/subscriptions/215abcdf-e871-479a-9d1c-17fpqr915095/resourceGroups/rg-uabcd12-0/providers/Microsoft.Network/networkInterfaces/nic-uabcd12-0/ipConfigurations/pip6-connection",
          etag: 'W/"96pqrcb9-1234-44fa-a93b-4d5812378d42"',
        },
      ],
      vnetEncryptionSupported: false,
      enableIPForwarding: false,
      tapConfigurations: [],
      primary: true,
      macAddress: "7C-AB-8D-D4-92-CD",
      hostedWorkloads: [],
      allowPort25Out: false,
      auxiliaryMode: "None",
      dnsSettings: {
        appliedDnsServers: [],
        dnsServers: [],
      },
      auxiliarySku: "None",
      virtualMachine: {
        id: "/subscriptions/215abcdf-e871-479a-9d1c-17fpqr915095/resourceGroups/rg-uabcd12-0/providers/Microsoft.Compute/virtualMachines/vm-uabcd12-0",
      },
      nicType: "Standard",
    },
    tags: null,
    identity: null,
    zones: null,
    extendedLocation: null,
  },
  {
    id: "/subscriptions/215abcdf-e871-479a-9d1c-17fpqr915095/resourcegroups/rg-uabcd12-0/providers/microsoft.network/networkinterfaces/nic-uabcd12-1",
    name: "nic-uabcd12-1",
    type: "microsoft.network/networkinterfaces",
    tenantId: "aabbccdd-eeff-gghh-iijj-123456789abc",
    kind: "Regular",
    location: "westus2",
    resourceGroup: "rg-uabcd12-0",
    subscriptionId: "215abcdf-e871-479a-9d1c-17fpqr915095",
    managedBy: "",
    sku: null,
    plan: null,
    properties: {
      provisioningState: "Succeeded",
      defaultOutboundConnectivityEnabled: false,
      enableAcceleratedNetworking: false,
      resourceGuid: "64bfc832-5824-4b89-b9be-57427dc0c216",
      disableTcpStateTracking: false,
      ipConfigurations: [
        {
          properties: {
            provisioningState: "Succeeded",
            privateIPAddressVersion: "IPv4",
            privateIPAllocationMethod: "Dynamic",
            privateIPAddress: "10.0.2.4",
            subnet: {
              id: "/subscriptions/215abcdf-e871-479a-9d1c-17fpqr915095/resourceGroups/rg-uabcd12-0/providers/Microsoft.Network/virtualNetworks/vnet-uabcd12/subnets/snet-uabcd12",
            },
            primary: true,
          },
          name: "testconfiguration1",
          type: "Microsoft.Network/networkInterfaces/ipConfigurations",
          id: "/subscriptions/215abcdf-e871-479a-9d1c-17fpqr915095/resourceGroups/rg-uabcd12-0/providers/Microsoft.Network/networkInterfaces/nic-uabcd12-1/ipConfigurations/testconfiguration1",
          etag: 'W/"6f7c6b87-5a24-pqr1-bcb3-416a1922ddd7"',
        },
      ],
      vnetEncryptionSupported: false,
      enableIPForwarding: false,
      tapConfigurations: [],
      primary: true,
      macAddress: "00-12-3A-AB-56-35",
      hostedWorkloads: [],
      allowPort25Out: false,
      auxiliaryMode: "None",
      dnsSettings: {
        appliedDnsServers: [],
        dnsServers: [],
      },
      auxiliarySku: "None",
      virtualMachine: {
        id: "/subscriptions/215abcdf-e871-479a-9d1c-17fpqr915095/resourceGroups/rg-uabcd12-0/providers/Microsoft.Compute/virtualMachines/vm-uabcd12-1",
      },
      nicType: "Standard",
    },
    tags: null,
    identity: null,
    zones: null,
    extendedLocation: null,
  },
  {
    id: "/subscriptions/215abcdf-e871-479a-9d1c-17fpqr915095/resourcegroups/rg-uabcd12-0/providers/microsoft.network/publicipaddresses/pip6-uabcd12",
    name: "pip6-uabcd12",
    type: "microsoft.network/publicipaddresses",
    tenantId: "aabbccdd-eeff-gghh-iijj-123456789abc",
    kind: "",
    location: "westus2",
    resourceGroup: "rg-uabcd12-0",
    subscriptionId: "215abcdf-e871-479a-9d1c-17fpqr915095",
    managedBy: "",
    sku: {
      name: "Standard",
      tier: "Regional",
    },
    plan: null,
    properties: {
      provisioningState: "Succeeded",
      resourceGuid: "d289b5bf-26e0-40b7-bce7-7ce5d7ed9bce",
      idleTimeoutInMinutes: 4,
      publicIPAllocationMethod: "Static",
      ipAddress: "1234:1030:d12:8::4a0",
      publicIPAddressVersion: "IPv6",
      ipConfiguration: {
        id: "/subscriptions/215abcdf-e871-479a-9d1c-17fpqr915095/resourceGroups/rg-uabcd12-0/providers/Microsoft.Network/networkInterfaces/nic-uabcd12-0/ipConfigurations/pip6-connection",
      },
      ipTags: [],
      ddosSettings: {
        protectionMode: "VirtualNetworkInherited",
      },
    },
    tags: {},
    identity: null,
    zones: ["1", "2", "3"],
    extendedLocation: null,
  },
  {
    id: "/subscriptions/215abcdf-e871-479a-9d1c-17fpqr915095/resourcegroups/rg-uabcd12-0/providers/microsoft.network/virtualnetworks/vnet-uabcd12",
    name: "vnet-uabcd12",
    type: "microsoft.network/virtualnetworks",
    tenantId: "aabbccdd-eeff-gghh-iijj-123456789abc",
    kind: "",
    location: "westus2",
    resourceGroup: "rg-uabcd12-0",
    subscriptionId: "215abcdf-e871-479a-9d1c-17fpqr915095",
    managedBy: "",
    sku: null,
    plan: null,
    properties: {
      provisioningState: "Succeeded",
      resourceGuid: "02f9c02d-7pqr-43c2-87f1-eb912343786c",
      privateEndpointVNetPolicies: "Disabled",
      virtualNetworkPeerings: [],
      enableDdosProtection: false,
      subnets: [
        {
          properties: {
            provisioningState: "Succeeded",
            ipConfigurations: [
              {
                id: "/subscriptions/215abcdf-e871-479a-9d1c-17fpqr915095/resourceGroups/RG-uabcd12-0/providers/Microsoft.Network/networkInterfaces/NIC-uabcd12-0/ipConfigurations/PIP6-CONNECTION",
              },
              {
                id: "/subscriptions/215abcdf-e871-479a-9d1c-17fpqr915095/resourceGroups/RG-uabcd12-0/providers/Microsoft.Network/networkInterfaces/NIC-uabcd12-0/ipConfigurations/TESTCONFIGURATION1",
              },
              {
                id: "/subscriptions/215abcdf-e871-479a-9d1c-17fpqr915095/resourceGroups/RG-uabcd12-0/providers/Microsoft.Network/networkInterfaces/NIC-uabcd12-1/ipConfigurations/TESTCONFIGURATION1",
              },
            ],
            privateLinkServiceNetworkPolicies: "Enabled",
            privateEndpointNetworkPolicies: "Disabled",
            delegations: [],
            addressPrefixes: ["10.0.2.0/24", "fd00:7ec4:2c41::/64"],
          },
          name: "snet-uabcd12",
          type: "Microsoft.Network/virtualNetworks/subnets",
          id: "/subscriptions/215abcdf-e871-479a-9d1c-17fpqr915095/resourceGroups/rg-uabcd12-0/providers/Microsoft.Network/virtualNetworks/vnet-uabcd12/subnets/snet-uabcd12",
          etag: 'W/"e6554620-2505-4f63-a64b-e400e3fea4df"',
        },
      ],
      addressSpace: {
        addressPrefixes: ["10.0.0.0/16", "fd00:7ec4:2c41::/48"],
      },
      dhcpOptions: {
        dnsServers: [],
      },
    },
    tags: null,
    identity: null,
    zones: null,
    extendedLocation: null,
  },
  {
    id: "/subscriptions/215abcdf-e871-479a-9d1c-17fpqr915095/resourcegroups/rg-uabcd12-0/providers/microsoft.storage/storageaccounts/stauabcd12",
    name: "stauabcd12",
    type: "microsoft.storage/storageaccounts",
    tenantId: "aabbccdd-eeff-gghh-iijj-123456789abc",
    kind: "StorageV2",
    location: "westus2",
    resourceGroup: "rg-uabcd12-0",
    subscriptionId: "215abcdf-e871-479a-9d1c-17fpqr915095",
    managedBy: "",
    sku: {
      name: "Standard_LRS",
      tier: "Standard",
    },
    plan: null,
    properties: {
      provisioningState: "Succeeded",
      encryption: {
        keySource: "Microsoft.Storage",
        services: {
          blob: {
            enabled: true,
            lastEnabledTime: "2026-02-06T13:43:58.2235204Z",
            keyType: "Account",
          },
          file: {
            enabled: true,
            lastEnabledTime: "2026-02-06T13:43:58.2235204Z",
            keyType: "Account",
          },
        },
      },
      privateEndpointConnections: [],
      supportsHttpsTrafficOnly: true,
      allowBlobPublicAccess: false,
      allowCrossTenantReplication: false,
      minimumTlsVersion: "TLS1_0",
      primaryEndpoints: {
        blob: "https://stauabcd12.blob.core.windows.net/",
        file: "https://stauabcd12.file.core.windows.net/",
        table: "https://stauabcd12.table.core.windows.net/",
        queue: "https://stauabcd12.queue.core.windows.net/",
        web: "https://stauabcd12.z5.web.core.windows.net/",
        dfs: "https://stauabcd12.dfs.core.windows.net/",
      },
      statusOfPrimary: "available",
      keyCreationTime: {
        key1: "2026-02-06T13:43:58.2079251Z",
        key2: "2026-02-06T13:43:58.2079251Z",
      },
      primaryLocation: "westus2",
      creationTime: "2026-02-06T13:43:57.9266658Z",
      networkAcls: {
        virtualNetworkRules: [],
        defaultAction: "Allow",
        ipv6Rules: [],
        ipRules: [],
        bypass: "AzureServices",
      },
      accessTier: "Hot",
      allowCrossTenantDelegationSas: false,
    },
    tags: {},
    identity: null,
    zones: null,
    extendedLocation: null,
  },
  {
    id: "/subscriptions/215abcdf-e871-479a-9d1c-17fpqr915095/resourcegroups/resgrp.with.period/providers/microsoft.managedidentity/userassignedidentities/uai-lemons",
    name: "uai-lemons",
    type: "microsoft.managedidentity/userassignedidentities",
    tenantId: "aabbccdd-eeff-gghh-iijj-123456789abc",
    kind: "",
    location: "eastus",
    resourceGroup: "resgrp.with.period",
    subscriptionId: "215abcdf-e871-479a-9d1c-17fpqr915095",
    managedBy: "",
    sku: null,
    plan: null,
    properties: {
      tenantId: "aabbccdd-eeff-gghh-iijj-123456789abc",
      isolationScope: "None",
      principalId: "e1ee1330-fd06-4732-a2c6-4d76d398831a",
      clientId: "136d3c27-c5bf-4083-af16-3eb4690d7136",
    },
    tags: {},
    identity: null,
    zones: null,
    extendedLocation: null,
  },
];
